### ISSUE TITLE
If you don't initialize the state you get null pointer

### ISSUE THREAD

**Issue by olsisaqe** [jakubkinst/Android-StatefulLayout#1]
If you don't create at all a reference of the StatefulLayout on your activity but just specify the layout in your xml then you receive a crash on the onSavedInstanceState where is trying to access the value of the state. A null check should be nice to have.

**Comment by jakubkinst** [comment]
Hey! Thanks. I fixed this weeks ago. I just didn't update the README file with the new version. Use 1.1.1.
